---
# vars file for imperva
imperva_major_version: '14.0.0'
imperva_var_freespace_gb: '28'
SeS_expected_patch_version: '12.0.0.80_0' #you can gather this from an upgraded system using impctl --version  This should be the set to the highest patch level of the old version BEFORE an upgrade.
expected_patch_file: 'SecureSphereV12.0.0-x86_64-Patch80_0.x'
patch_timeout: '2400'
